config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :news
    
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :news do
    resources :comments, only: [:create]
  end

  root "news#index"
    
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/news.rb
class News < ApplicationRecord
  belongs_to :user
  has_many :comments ,dependent: :destroy
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: %i[ show edit update destroy ]
  before_action only: [:new, :create] do
    authorize_request(["author", "admin"])
   end
  before_action only: [:edit, :update, :destroy] do
    authorize_request(["admin"])
   end
    

  # GET /news or /news.json
    def index
      @news = News.includes(:comments).all
      @comment = Comment.new # Inicializa un nuevo comentario para el formulario
    end
  

  # GET /news/1 or /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news or /news.json
  def create
    @news = News.new(news_params)
    @news.user_id = current_user.id

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: "News was successfully created." }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1 or /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: "News was successfully updated." }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1 or /news/1.json
  def destroy
    @news.destroy!

    respond_to do |format|
      format.html { redirect_to news_index_path, status: :see_other, notice: "News was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to news_index_path, alert: 'Noticia no encontrada.'   
    end

    # Only allow a list of trusted parameters through.
    def news_params
      params.require(:news).permit(:title, :content, :user_id)
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= form_with(model: news) do |form| %>
  <% if news.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
        <% news.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/news/_news.html.erb
<div id="<%= dom_id news %>">
  <p>
    <strong>Title:</strong>
    <%= news.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= news.content %>
  </p>

  <p>
    <strong>User:</strong>
    <%= news.user.email %>
  </p>

</div>

app/views/news/edit.html.erb
<% content_for :title, "Editing news" %>

<h1>Editing news</h1>

<%= render "form", news: @news %>

<br>

<div>
  <%= link_to "Show this news", @news %> |
  <%= link_to "Back to news", news_index_path %>
</div>

app/views/news/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "News" %>

<h1>Listado de Noticias</h1>

<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>


<% @news.each do |news_item| %>
  <div class="news-item">
    <h2><%= news_item.title %></h2>
    <p><%= news_item.content %></p>

    <h3>Comentarios:</h3>
    <div class="comments">
      <% news_item.comments.each do |comment| %>
        <p>comentario: <%= comment.content%></p>
      <% end %>
    </div>

    <!-- Formulario para agregar un nuevo comentario -->
    <%= form_with(model: [news_item, news_item.comments.build], local: true) do |f| %>
      <div class="form-group">
        <%= f.label :content, "Nuevo Comentario" %>
        <%= f.text_area :content, class: 'form-control' %>
      </div>
      <%= f.submit "Agregar Comentario", class: 'btn btn-primary' %>
    <% end %>
  </div>
<% end %>

app/views/news/new.html.erb
<% content_for :title, "New news" %>

<h1>New news</h1>

<%= render "form", news: @news %>

<br>

<div>
  <%= link_to "Back to news", news_index_path %>
</div>

app/views/news/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @news %>

<div>
  <%= link_to "Edit this news", edit_news_path(@news) %> |
  <%= link_to "Back to news", news_index_path %>

  <%= button_to "Destroy this news", @news, method: :delete %>
</div>
<%= form_with(model: [@new, Comment.new]) do |form| %>

  <div>
    <%= form.label :content, "Nuevo comentario" %>
    <%= form.text_area :content %>
  </div>
  <div>
    <%= form.submit 'Comentar' %>
  </div>
<% end %>